server:
  port: 8080
  servlet:
    context-path: /dataxs

      logging:
        pattern:
          dateformat: "-[yyyy-MM-dd HH:mm:ss.S]"
        file:
          path: /opt/local/logs/
      spring:
        redis:
          # Redis服务器地址
          host: 192.168.16.80
          # Redis服务器连接端口
          port: 6379
          # Redis服务器连接密码（默认为空）
          password: 123456

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${MYSQL_HOST:172.16.56.80}:${MYSQL_PORT:3306}/datax-plus?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.dataxservice.demo.mybatis.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true