server:
  port: 8080
  servlet:
    context-path: /dataxs

logging:
  pattern:
  file:
    path: /opt/local/logs/
spring:
  redis:
    # Redis服务器地址
    host: redis
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456